.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GREPORD" "1" "November 2021" "" ""
.
.SH "NAME"
\fBgrepord\fR
.
.P
grepord \fIgrep arguments\fR… [\-sort:[<fs\.Stats property>][,][(desc|asc)][,][\fIlimit number\fR]]
.
.P
Grepord requires grep to already be installed\. Type grep \-h to check if grep is installed\.
.
.P
To use this program, you must enter grep arguments that will return file paths\. Example: grepord \-iRl \'\./\' \-e \'hello world\'
.
.P
You can sort by the properties of fs\.Stats\. See: https://nodejs\.org/api/fs\.html#fs_class_fs_stats
.
.P
The default sort is mtime descending\. The format for changing the sort is \-sort: as the last argument, with an optional fs\.Stats property, a comma, an optional desc or asc, a comma and then an optional limit number (This operates the same way as the SQL LIMIT/TOP clause)\. Example: grepord \-iRl \'\./\' \-e \'hello world\' \-sort:size,asc,10
.
.P
Author: Peter Keller Contact: peterkeller@protonmail\.com License: MIT Bugs: https://github\.com/petekeller2/grepord/issues
