
name: New Release

on:
  push:
    paths:
      - 'CHANGELOG.md'

  workflow_dispatch:

jobs:
  tagged-release:
    name: "New Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
